apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          image: dmitrymomot/skapi:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: api-config
          ports:
            - name: api-port
              containerPort: 8080
